### 로그인
# 응답: Access Token → Body, Refresh Token → HttpOnly Cookie(refresh_token) 자동 저장
POST {{domain-gateway}}/api/v1/auth/login
Content-Type: {{json}}

{
  "loginId" : "vhkdrb521",
  "password" : "ghkddlsrb1!"
}

> {%
  client.global.set("accessToken", response.body.data.accessToken);
%}

### 아이디 찾기
GET {{domain-gateway}}/api/v1/member/find/me
Content-Type: application/json

{
  "memberName": "퐝퐝규",
  "phoneNumber": "01049045402"
}

### 회원 정보 수정
POST {{domain-gateway}}/api/v1/member/modify
Content-Type: application/json

{
  "phoneNumber": "",
  "email": ""
}

### 회원 탈퇴
DELETE {{domain-gateway}}/api/v1/member/withdraw