### 로그인
# 응답: Access Token → Body, Refresh Token → HttpOnly Cookie(refresh_token) 자동 저장
POST {{domain-gateway}}/api/v1/auth/login
Content-Type: {{json}}

{
    "loginId" : "vhkdrb521",
    "password" : "ghkddlsrb1!"
}

> {%
    client.global.set("accessToken", response.body.data.accessToken);
%}

### JWT로 회원 조회
POST {{domain-gateway}}/api/v1/member/jwt
Content-Type: {{json}}
Authorization: Bearer {{accessToken}}

{
    "jwt": "{{accessToken}}"
}

### memberId로 회원 조회
POST {{domain-gateway}}/api/v1/member/id
Content-Type: {{json}}
Authorization: Bearer {{accessToken}}

{
    "memberId": "ac150006-9ce7-193d-819c-e759d6340000"
}

### loginId 로 회원 조회
POST {{domain-gateway}}/api/v1/member/login-id
Content-Type: {{json}}
Authorization: Bearer {{accessToken}}

{
    "loginId": "vhkdrb521"
}

### email 로 회원 조회
POST {{domain-gateway}}/api/v1/member/email
Content-Type: {{json}}
Authorization: Bearer {{accessToken}}

{
    "email": "vhkdrb521@gmail.com"
}
