### JWT로 회원 조회
POST {{domain-gateway}}/api/v1/member/jwt
Content-Type: {{json}}
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhYzE1MDAwNi05Y2U3LTE5M2QtODE5Yy1lNzU5ZDYzNDAwMDAiLCJsb2dpbklkIjoidmhrZHJiNTIiLCJlbWFpbCI6InZoa2RyYjUyQGdtYWlsLmNvbSIsIm1lbWJlclR5cGUiOiJNRU1CRVIiLCJlbWFpbFZlcmlmaWVkIjp0cnVlLCJpYXQiOjE3NzM1MDU1NDEsImV4cCI6MTc3MzUwOTE0MX0.JA-sI71Nr58pUsUfzEo4bDhBPpUinrNjd0HuGvY4IpSfoH0Dp6p1i5TX3itg1fRaAZIBbMQcCLWwPePvP1tvvQ

{
    "jwt": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhYzE1MDAwNi05Y2U3LTE5M2QtODE5Yy1lNzU5ZDYzNDAwMDAiLCJsb2dpbklkIjoidmhrZHJiNTIiLCJlbWFpbCI6InZoa2RyYjUyQGdtYWlsLmNvbSIsIm1lbWJlclR5cGUiOiJNRU1CRVIiLCJlbWFpbFZlcmlmaWVkIjp0cnVlLCJpYXQiOjE3NzM1MDU1NDEsImV4cCI6MTc3MzUwOTE0MX0.JA-sI71Nr58pUsUfzEo4bDhBPpUinrNjd0HuGvY4IpSfoH0Dp6p1i5TX3itg1fRaAZIBbMQcCLWwPePvP1tvvQ"
}
