### 로그인
POST {{domain-gateway}}/api/v1/auth/login
Content-Type: {{json}}

{
    "loginId" : "vhkdrb521",
    "password" : "ghkddlsrb1!"
}

> {%
  client.global.set("accessToken", response.body.data.accessToken);
%}

### 단건 일반 등록
POST {{domain-gateway}}/api/v1/stop/{test}
Content-Type: {{json}}
Authorization: Bearer {{accessToken}}


### 초기 bulk 등록
POST {{domain-gateway}}/api/v1/stop/register/bulk
Content-Type: {{json}}
Authorization: Bearer {{accessToken}}
